name: 'Initialization of all packages'
description: 'Initialize all the modules and generate files'

runs:
  using: 'composite'
  steps:
    - name: 📥 go mod tidy
      shell: bash
      run: go mod tidy

    - name: 🛠️ go generate
      shell: bash
      env:
        GOFLAGS: -mod=mod
      run: |
        set -Eeuo pipefail
        mkdir -p target tmp
        go generate ./...